# app:
#   build: .
#   command: python -u app.py
#   ports:
#     - "5000:5000"
#   volumes:
#     - .:/app
#   depends_on:
#     - db
# db:
#     image: postgres:14.1
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 12345
#       POSTGRES_DB: Test
#     ports:
#       - 5432:5432
    
      
version: '3.6'

services:
  api:
    build: .
    depends_on:
      - db
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - .:/app
      
    restart: always

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Test
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data